name: "Spreadsheet to Issue Action"
description: "GoogleスプレッドシートからGitHub Issueを自動作成するComposite Action"
author: "tooppoo"

inputs:
  github_token:
    description: "GitHub Issues作成用トークン"
    required: true
  spreadsheet_id:
    description: "SpreadsheetドキュメントID"
    required: true
  sheet_name:
    description: "シート名（タブ名）"
    required: true
  title_template:
    description: "Issueタイトルのmustacheテンプレート"
    required: true
  body_template:
    description: "Issue本文のmustacheテンプレート"
    required: true
  sync_column:
    description: '連携済み判定/書き戻し列（例: "E"）'
    required: true
  labels:
    description: "付与ラベル（JSON配列またはカンマ区切り）"
    required: false
    default: ""
  max_issues_per_run:
    description: "1回に作成する最大件数（0以下やNaNは無制限として扱う）"
    required: false
    default: "10"
  rate_limit_delay:
    description: "1件ごとの待機ミリ秒"
    required: false
    default: "1000"
  read_range:
    description: '取得範囲（列文字で始まるA1範囲のみ対応。例: "A:Z", "C5:F"。行のみの範囲 "5:10" 等は非対応）'
    required: false
    default: "A:Z"
  data_start_row:
    description: "データ開始行（1行目はヘッダ）。1未満の値はエラー。未指定や数値でない場合は2にフォールバック"
    required: false
    default: "2"
  boolean_truthy_values:
    description: "既連携判定のtruthy集合（JSON配列）"
    required: false
    default: '["TRUE","true","True","1","はい","済"]'
  dry_run:
    description: "作成/書戻しを行わずログのみ"
    required: false
    default: "false"

outputs:
  processed_count:
    description: "処理行数"
    value: ${{ steps.run.outputs.processed_count }}
  created_count:
    description: "作成件数"
    value: ${{ steps.run.outputs.created_count }}
  skipped_count:
    description: "スキップ件数"
    value: ${{ steps.run.outputs.skipped_count }}
  failed_count:
    description: "失敗件数"
    value: ${{ steps.run.outputs.failed_count }}
  created_issue_urls:
    description: "作成IssueのURL配列（最大100件）"
    value: ${{ steps.run.outputs.created_issue_urls }}
  summary_markdown:
    description: "集計とURL一覧のサマリーMarkdown"
    value: ${{ steps.run.outputs.summary_markdown }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "pnpm"
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Build
      run: pnpm build
      shell: bash
    - id: run
      name: Run sync script
      run: node dist/index.js
      shell: bash
      env:
        # Inputs
        GITHUB_TOKEN: ${{ inputs.github_token }}
        SPREADSHEET_ID: ${{ inputs.spreadsheet_id }}
        SHEET_NAME: ${{ inputs.sheet_name }}
        TITLE_TEMPLATE: ${{ inputs.title_template }}
        BODY_TEMPLATE: ${{ inputs.body_template }}
        LABELS: ${{ inputs.labels }}
        MAX_ISSUES_PER_RUN: ${{ inputs.max_issues_per_run }}
        RATE_LIMIT_DELAY: ${{ inputs.rate_limit_delay }}
        SYNC_COLUMN: ${{ inputs.sync_column }}
        READ_RANGE: ${{ inputs.read_range }}
        DATA_START_ROW: ${{ inputs.data_start_row }}
        BOOLEAN_TRUTHY_VALUES: ${{ inputs.boolean_truthy_values }}
        DRY_RUN: ${{ inputs.dry_run }}
        # Inherit Google access token from caller's OIDC step
        GOOGLE_OAUTH_ACCESS_TOKEN: ${{ env.GOOGLE_OAUTH_ACCESS_TOKEN }}
