name: Scheduled Spreadsheet Sync

on:
  schedule:
    # Run every 30 minutes as specified in the requirements
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run in dry-run mode'
        required: false
        default: false
        type: boolean

jobs:
  sync:
    uses: ./.github/workflows/sync-spreadsheet-to-issues.yml
    with:
      config_path: '.github/spreadsheet-sync-config.json'
      sync_state_path: '.github/sync-state.json'
      google_service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      wif_provider: ${{ vars.WIF_PROVIDER }}
      max_issues_per_run: 50
      rate_limit_delay: 0.33  # 3 requests per second as specified
      dry_run: ${{ github.event.inputs.dry_run == 'true' }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}